config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "reports#index"
  get 'reports', to: 'reports#index', as: 'reports'
  get 'users', to: 'users#index', as: 'users'
  delete 'users/:id', to: 'users#destroy', as: 'delete_user'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/daily_record.rb
class DailyRecord < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  self.primary_key = 'id'

  MALE = 'male'
  FEMALE = 'female'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  def index
    @reports = ListReport.new(params).call
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = ListUser.new(params).call
  end

  def destroy
    @user = User.find(params[:id])
    if @user.destroy
      CountUserDaily.new(today: @user.created_at).call
      UpdateUserCount.new(time: @user.created_at).call
      redirect_to root_path, notice: 'User was successfully deleted.'
    else
      redirect_to root_path, alert: 'User fails to delete.'
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ProjectAssignment</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
  </head>

  <body>
    <header class="navbar sticky-top bg-dark flex-md-nowrap p-0 shadow" data-bs-theme="dark">
      <a class="navbar-brand col-md-3 col-lg-2 me-0 px-3 fs-6 text-white" href="#">PSY.AI</a>
    </header>
    <div class='container-fluid'>
      <div class='row'>
        <div class="sidebar border border-right col-md-3 col-lg-2 p-0 bg-body-tertiary">
          <ul class="nav flex-column">
            <li class="nav-item">
              <%= link_to 'Dashboard', root_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to 'List Users', users_path, class: "nav-link" %>
            </li>
          </ul>
        </div>
        <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
          <%= yield %>
        </main>
      </div>
    </div>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
  </body>
</html>

app/views/reports/index.html.erb
<div class="align-items-center pt-3 pb-2 mb-3">
  <div class='row'>
    <div class='col-12'>
      <h1 class="h2">List Daily Report (<%= @reports.count %>)</h1>
      <br/>
    </div>
    <div class='col-12' style="margin-bottom:50px;">
      <canvas id="dateReportChart" width="800" height="400"></canvas>
    </div>
    <div class='col-12'>
      <%= form_with(url: reports_path, method: "get", local: true) do |form| %>
        <div class='row'>
          <div class="col-5">
            <%= form.date_field :start_date, value: params[:start_date], placeholder: "Start Date...", class: 'form-control' %>
          </div>
          <div class="col-5">
            <%= form.date_field :end_date, value: params[:end_date], placeholder: "End Date...", class: 'form-control' %>
          </div>
          <div class="col-2">
            <input type="submit" value="Search" class='btn btn-primary' style="width:100%">
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>
<div class="table-responsive small">
  <table class="table table-striped-columns">
    <thead>
      <tr>
        <th scope="col">Date</th>
        <th scope="col">Male Count</th>
        <th scope="col">Female Count</th>
        <th scope="col">Male AVG Age</th>
        <th scope="col">Female AVG Age</th>
        <th scope="col">Created At</th>
      </tr>
    </thead>
    <tbody>
      <% @reports.each do |r| %>
        <tr>
          <td><%= r.date %></td>
          <td><%= r.male_count %></td>
          <td><%= r.female_count %></td>
          <td><%= r.male_avg_age %></td>
          <td><%= r.female_avg_age %></td>
          <td><%= r.created_at %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
<script>
  var ctx = document.getElementById('dateReportChart').getContext('2d');
  var dateReportChart = new Chart(ctx, {
    type: 'line',
    data: {
      labels: <%= raw @reports.pluck(:date).to_json %>,
      datasets: [
      {
        label: 'Male Count',
        data:  <%= @reports.pluck(:male_count) %>,
        borderColor: 'rgba(54, 162, 235, 1)',
        backgroundColor: 'rgba(54, 162, 235, 0.2)',
        borderWidth: 1
      },
      {
        label: 'Female Count',
        data:  <%= @reports.pluck(:female_count) %>,
        borderColor: 'rgba(54, 162, 235, 1)',
        backgroundColor: 'rgba(54, 162, 235, 0.2)',
        borderWidth: 1
      },
      {
        label: 'Male AVG Age',
        data: <%= @reports.pluck(:male_avg_age) %>,
        borderColor: 'rgba(75, 192, 192, 1)',
        backgroundColor: 'rgba(75, 192, 192, 0.2)',
        borderWidth: 1
      },
      {
        label: 'Female AVG Age',
        data: <%= @reports.pluck(:female_avg_age) %>,
        borderColor: 'rgba(75, 192, 192, 1)',
        backgroundColor: 'rgba(75, 192, 192, 0.2)',
        borderWidth: 1
      }
      ]
    },
    options: {
      scales: {
        y: {
          beginAtZero: true
        }
      }
    }
  });
</script>

app/views/users/index.html.erb
<div class="align-items-center pt-3 pb-2 mb-3">
  <div class='row'>
    <div class='col-12'>
      <h1 class="h2">List Users (<%= @users.count %>)</h1>
      <br/>
    </div>
    <div class='col-12'>
      <%= form_with(url: users_path, method: "get", local: true) do |form| %>
        <div class='row'>
          <div class="col-4">
            <%= form.text_field :keywords, value: params[:keywords], placeholder: "Search...", class: 'form-control' %>
          </div>
          <div class="col-3">
            <%= form.text_field :location, value: params[:location], placeholder: "Country or City...", class: 'form-control' %>
          </div>
          <div class="col-3">
            <%= form.text_field :gender, value: params[:gender], placeholder: "Gender...", class: 'form-control' %>
          </div>
          <div class="col-2">
            <input type="submit" value="Search" class='btn btn-primary' style="width:100%">
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>
<div class="table-responsive small">
  <table class="table table-striped-columns">
    <thead>
      <tr>
        <th scope="col">UUID</th>
        <th scope="col">Name</th>
        <th scope="col">Location</th>
        <th scope="col">Gender</th>
        <th scope="col">Age</th>
        <th scope="col">Delete</th>
      </tr>
    </thead>
    <tbody>
      <% @users.each do |user| %>
        <tr>
          <th scope="row"><%= user.uuid %></th>
          <td><%= user.name['title'] %>.<%= user.name['first'] %> <%= user.name['last'] %></td>
          <td><%= user.location['city'] %>, <%= user.location['street']['name'] %>, <%= user.location['country'] %></td>
          <td><%= user.gender %></td>
          <td><%= user.age %></td>
          <td><%= button_to "Delete", delete_user_path(user), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-danger" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>